<script setup lang="ts">
import { CircleDollarSign, ReceiptText, Search, TriangleAlert } from "lucide-vue-next";
import Column from "primevue/column";import DataTable from "primevue/datatable";import InputText from "primevue/inputtext";import Select from "primevue/select";import Tag from "primevue/tag";
import {onBeforeUnmount,onMounted,ref,watch}from"vue";
import{operacionPrincipalService,type FacturacionPrincipal}from"@/api/services/operacion-principal.service";
import TituloConAyuda from"@/components/shared/TituloConAyuda.vue";import{Card,CardContent}from"@/components/ui/card";import{Skeleton}from"@/components/ui/skeleton";
const cargando=ref(true),error=ref(""),busqueda=ref(""),estado=ref("TODOS"),pagina=ref(1),porPagina=ref(10),total=ref(0);const datos=ref<FacturacionPrincipal[]>([]);const resumen=ref({facturado:0,cobrado:0,pendiente:0});let timer:ReturnType<typeof setTimeout>|undefined;
const dinero=(v:number,m="PEN")=>new Intl.NumberFormat("es-PE",{style:"currency",currency:m.trim()||"PEN"}).format(v);const fecha=(v:string|null)=>v?new Intl.DateTimeFormat("es-PE",{dateStyle:"medium"}).format(new Date(v)):"—";const severidad=(v:string)=>["PAGADA","PAGADO","APROBADO"].includes(v)?"success":["VENCIDA","FALLIDA"].includes(v)?"danger":"warn";
async function cargar(){cargando.value=true;error.value="";try{const r=await operacionPrincipalService.facturacion({pagina:pagina.value,porPagina:porPagina.value,buscar:busqueda.value,estado:estado.value});datos.value=r.datos;total.value=r.total;resumen.value=r.resumen;}catch(c){error.value=c instanceof Error?c.message:"No se pudo cargar la facturación.";}finally{cargando.value=false;}}
function cambiarPagina(e:{first:number;rows:number}){porPagina.value=e.rows;pagina.value=Math.floor(e.first/e.rows)+1;void cargar();}watch([busqueda,estado],()=>{if(timer)clearTimeout(timer);timer=setTimeout(()=>{pagina.value=1;void cargar();},350)});onMounted(()=>void cargar());onBeforeUnmount(()=>{if(timer)clearTimeout(timer)});
</script>
<template><section class="mx-auto grid max-w-400 gap-6"><TituloConAyuda clase-eyebrow="text-primary" eyebrow="Control financiero" titulo="Facturación" ayuda="Órdenes y pagos reales registrados en Supabase; la conciliación externa se conectará con Izipay."/><div v-if="error" class="border-l-4 border-l-red-500 bg-red-500/10 p-4 text-sm font-semibold">{{error}}</div>
<div class="grid gap-4 sm:grid-cols-3"><Skeleton v-if="cargando" v-for="i in 3" :key="i" class="h-24"/><Card v-else v-for="x in [{e:'Facturado',v:resumen.facturado,i:ReceiptText},{e:'Cobrado',v:resumen.cobrado,i:CircleDollarSign},{e:'Pendiente',v:resumen.pendiente,i:TriangleAlert}]" :key="x.e"><CardContent class="flex gap-4 p-5"><component :is="x.i" class="h-6 w-6 text-primary"/><div><strong class="text-2xl font-black">{{dinero(x.v)}}</strong><p class="text-xs text-muted-foreground">{{x.e}}</p></div></CardContent></Card></div>
<Card><CardContent class="p-0"><div class="grid gap-3 border-b border-border p-5 md:grid-cols-[1fr_16rem]"><label class="relative"><Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2"/><InputText v-model="busqueda" class="filtro-control w-full pl-10" placeholder="Orden, organización o concepto"/></label><Select v-model="estado" :options="[{label:'Todos',value:'TODOS'},{label:'Pagada',value:'PAGADA'},{label:'Pendiente',value:'PENDIENTE'},{label:'Vencida',value:'VENCIDA'}]" option-label="label" option-value="value" class="filtro-control"/></div><div v-if="cargando" class="space-y-2 p-5"><Skeleton v-for="i in 5" :key="i" class="h-12"/></div><DataTable v-else :value="datos" data-key="id" lazy paginator :first="(pagina-1)*porPagina" :rows="porPagina" :total-records="total" :rows-per-page-options="[10,20,50]" class="tabla-administracion" scrollable table-style="min-width:72rem" @page="cambiarPagina"><template #empty><div class="py-10 text-center">No existen órdenes.</div></template><Column field="numero" header="Orden"/><Column field="organizacion" header="Organización"/><Column field="concepto" header="Concepto"/><Column header="Emisión"><template #body="{data}">{{fecha(data.creadaEn)}}</template></Column><Column header="Vencimiento"><template #body="{data}">{{fecha(data.expiraEn)}}</template></Column><Column header="Total"><template #body="{data}"><b>{{dinero(data.total,data.moneda)}}</b></template></Column><Column header="Estado"><template #body="{data}"><Tag :severity="severidad(data.estadoPago||data.estado)" :value="data.estadoPago||data.estado"/></template></Column><Column field="proveedor" header="Proveedor"/></DataTable></CardContent></Card></section></template>
